apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData: # Use stringData para dados que não precisam ser base64 encodados previamente
  mongo-root-username: admin
  mongo-root-password: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce # O volume pode ser montado como leitura/escrita por um único nó.
  resources:
    requests:
      storage: 10Gi # Solicita 10 GB de armazenamento.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1 # Número de réplicas do pod
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db # armazenamento do mongo
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017         # Porta que o Service irá expor
      targetPort: 27017   # Porta no container para onde o tráfego será redirecionado
  type: ClusterIP         # Tipo de Service. ClusterIP é o padrão e expõe o Service apenas internamente no cluster.