apiVersion: v1
kind: Secret
metadata: # Define o segredo para armazenar as credenciais do MongoDB
  name: mongodb-secret
type: Opaque
stringData: # Define os dados secretos para o MongoDB
  mongo-root-username: admin
  mongo-root-password: password
---
apiVersion: v1 
kind: PersistentVolumeClaim # Define a Reivindicação de Volume Persistente
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce # O volume pode ser montado como leitura/escrita por um único nó.
  resources:
    requests:
      storage: 10Gi # Solicita 10 GB de armazenamento.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1 # Número de réplicas do pod
  selector:
    matchLabels:
      app: mongodb
  template: # Define o template do pod
    metadata:
      labels:
        app: mongodb
    spec: 
      containers: # define os containers que serão executados no pod
      - name: mongodb
        image: mongo:latest
        ports: # porta do container
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME # variável de ambiente para o nome do usuário root
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD # variável de ambiente para a senha do usuário root
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts: # monta o volume persistente no container
        - name: mongodb-persistent-storage
          mountPath: /data/db # armazenamento do mongo
      volumes: # define os volumes que serão montados no pod
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata: # Define o serviço
  name: mongodb-service
  labels:
    app: mongodb
spec:     # Especifica o tipo de serviço
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017         # porta que o Service irá expor
      targetPort: 27017   # porta no container para onde o tráfego será redirecionado
  type: ClusterIP         # tipo do service