apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  # Labels para identificar e organizar o recurso
  labels:
    app: nodeapp
# Especificações do Deployment
spec:
  # Número de pods que devem estar rodando
  replicas: 1
  # Seletor que define quais pods este deployment gerencia
  selector:
    matchLabels:
      app: nodeapp 
  template: # Template para criação dos pods
    metadata:
      labels:
        app: nodeapp
    spec: # Especificações dos pods
      # Lista de containers que rodarão no pod
      containers:
        - name: nodeserver # nome do container
          # Imagem customizada criada no Docker Hub
          image: pedrolshernandes/api-p2:latest #meuusergithub/repositorio:tag
          ports: # Portas expostas pelo container
            - containerPort: 5000 #porta do container

---
# Service para expor a aplicação Node.js para fora do cluster
apiVersion: v1
kind: Service
metadata:
  name: backend
spec: # Especificações do Service
  type: NodePort # Tipo de serviço que expõe a aplicação em uma porta específica do nó
  # Configuração das portas
  ports:
    - port: 5000               #porta dentro do container
      targetPort: 5000         #porta do container
      nodePort: 30085        #porta no host(mapeada)
  # Seletor para conectar com os pods corretos
  selector:
    app: nodeapp #conecta com os pods